ci/docs: fix permissions for mdbook-linkcheck
Recent failures in the docs workflow (see
https://github.com/input-output-hk/jormungandr/runs/2506718320) were
caused by a permissions issue:

        Error: -05 06:06:26 [ERROR] (mdbook::utils): Error: Rendering failed
        Error: -05 06:06:26 [ERROR] (mdbook::utils): 	Caused By: Unable to start the backend
        Error: -05 06:06:26 [ERROR] (mdbook::utils): 	Caused By: Permission denied (os error 13)
        Error: Process completed with exit code 101.

After unzipping files do not have the permissions that allow executing
them, see example from my machine after reproducing that workflow:

        total 12212
        -rw-r--r--. 1 1070 Feb 26 17:35 LICENSE
        -rw-r--r--. 1 12489480 Feb 26 17:35 mdbook-linkcheck
        -rw-r--r--. 1 5238 Feb 26 17:35 README.md